openapi: 3.0.1
info:
  title: Messages-crud
  description: 'Messages-проект - это проект для работы с сущностью messages'
  license:
    name: MIT open source license
    url: https://github.com/otuskotlin/202105-otuskotlin-marketplace/blob/main/LICENSE
  version: 0.0.1
servers:
  - url: https://localhost/
tags:
  - name: messages-crud
    description: CRUDS для сообщений
  - name: offers
    description: создание, обновление, чтение, удаление и поиск сообщений
paths:
  /messages/create:
    post:
      tags:
        - message
      summary: создать сообщение
      operationId: createMessage
      requestBody:
        description: Объект запроса для создания сообщения
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMessageRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMessageResponse'

  /messages/read:
    post:
      tags:
        - message
      summary: Получить информацию об объявлении
      operationId: readMessage
      requestBody:
        description: Объект запроса для получения информации об объявлении
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadMessageRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadMessageResponse'
  /messages/update:
    post:
      tags:
        - message
      summary: Обновить объявление
      operationId: updateAd
      requestBody:
        description: Объект запроса для обновления объявления
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMessageRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMessageResponse'
  /messages/delete:
    post:
      tags:
        - message
      summary: Удалить объявление
      operationId: deleteAd
      requestBody:
        description: Объект запроса для удаления объявления
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteMessageRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteMessageResponse'
  /messages/search:
    post:
      tags:
        - message
      summary: Поиск объявлений
      operationId: searchAd
      requestBody:
        description: Объект запроса для поиска объявлений
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchMessageRequest'
        required: true
      responses:
        200:
          description: all responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchMessageResponse'

components:
  schemas:

    BaseMessage:
      type: object
      description: Базовый класс как для запросов, так и для ответов
      properties:
        messageType:
          type: string
          title: Дискриминатор
          description: Дискриминатор, содержащий тип класса сообщения и использующийся для десериализации
      discriminator:
        propertyName: messageType

    BaseRequest:
      description: Базовый класс для всех запросов
      properties:
        requestId:
          type: string
        payload:
          type: string

    BaseResponse:
      description: Базовый класс для всех ответов
      allOf:
        #        - $ref: '#/components/schemas/BaseMessage'
        - type: object
          properties:
            requestId:
              type: string
            result:
              type: string
              enum:
                - success
                - error
            errors:
              type: array
              items:
                $ref: '#/components/schemas/RequestError'

    RequestError:
      type: object
      description: Описание ошибки обработки запроса
      properties:
        message:
          type: string
        field:
          type: string

    AdVisibility:
      type: string
      description: 'Тип видимости объявления. Возможные значения: видит только владелец, только зарегистрированный в системе пользователь, видимо всем'
      enum:
        - ownerOnly
        - registeredOnly
        - public

    AdDealSide:
      type: string
      description: 'Указание на сторону сделки объявления: предложение или потребность'
      enum:
        - demand
        - proposal

    CreateableAd:
      type: object
      description: Структура с данными об объявлении для запроса о созадии
      properties:
        title:
          type: string
          title: Заголовок объявления
          description: Краткое название объявления
        description:
          type: string
          title: Описание объявления
          description: Тело объявления с описанием особенностей выставляемой заявки
        ownerId:
          type: string
          title: Идентификатор владельца объявления
          description: Идентификатор пользователя, который создал и управляет объявлением
        visibility:
          $ref: '#/components/schemas/AdVisibility'
        dealSide:
          $ref: '#/components/schemas/AdDealSide'

    UpdateableAd:
      description: Структура для данных об объявлении в запросе на обновление
      allOf:
        - $ref: '#/components/schemas/CreateableAd'
        - type: object
          properties:
            id:
              type: string
              description: Идентификатор объявления

    ResponseAd:
      description: Структура, описывающая объявление в ответе
      allOf:
        - $ref: '#/components/schemas/UpdateableAd'
        - type: object
          properties:
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/AdPermissions'

    ResponseMessage:
      description: Структура, описывающая сообщения
      properties:
        payload:
          type: string


    AdPermissions:
      type: string
      description: Доступы к операциям над объявлением
      enum:
        - read
        - update
        - contact

    BaseDebugRequest:
      type: object
      description: Структура с описанием отладочных параметров запроса
      properties:
        mode:
          type: string
          default: prod
          enum:
            - prod
            - test
            - stub

    BasePaginatedRequest:
      type: object
      description: Структура с описанием запрашиваемой страницы в запросах списков
      properties:
        size:
          type: integer
          description: Размер запрашиваемой страницы
          format: int32
        lastId:
          type: string
          description: Идентификатор последнего объекта предыдущей страницы

    BasePaginatedResponse:
      type: object
      description: Структура с описанием страницы в ответе
      properties:
        size:
          type: integer
          description: Размер запрашиваемой страницы
          format: int32
        lastId:
          type: string
          description: Идентификатор последнего объекта предыдущей страницы
        position:
          type: string
          enum:
            - first
            - middle
            - last

    InitAdRequest:
      description: Структура для запроса начального состояния при старте вэб-клиента
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'

    CreateMessageRequest:
      description: Структура для создания сообщения в репоизтории
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'



    InitAdResponse:
      description: Структура для ответа с начальным состоянием при старте вэб-клиента
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
    CreateMessageResponse:
      description: Структура для ответа с начальным состоянием при старте вэб-клиента
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object

    CreateAdRequest:
      description: Структура для запроса создания нового объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            createAd:
              $ref: '#/components/schemas/CreateableAd'
            debug:
              allOf:
                - $ref: '#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyTitle
                        - databaseError

    CreateAdResponse:
      description: Структура для ответа на запрос о создании объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            createdAd:
              $ref: '#/components/schemas/ResponseAd'



    ReadAdRequest:
      description: Структура для получения объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            readAdId:
              type: string
            debug:
              allOf:
                - $ref: '#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - databaseError
    ReadMessageRequest:
      description: Структура для получения объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            Id:
              type: string
            debug:
              allOf:
                - $ref: '#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - databaseError
    ReadMessageResponse:
      description: Структура для ответа на запрос с информацией об объявлении
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            id:
              type: string
            payload:
              type: string

    UpdateMessageRequest:
      description: Структура для запроса обновления существующего объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            createMessage:
              type: string
            id:
              type: string
            payload:
              type: string
            debug:
              allOf:
                - $ref: '#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyTitle
                        - databaseError

    UpdateMessageResponse:
      description: Структура для ответа на запрос с информацией об объявлении
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            payload:
              type: string


    DeleteMessageRequest:
      description: Структура для запроса удаления объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            id:
              type: string
            debug:
              allOf:
                - $ref: '#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - databaseError

    DeleteMessageResponse:
      description: Структура для ответа на запрос об удалении объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            payload:
              type: string

    SearchMessageRequest:
      description: Структура для запроса поиска объявлений
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            page:
              $ref: '#/components/schemas/BasePaginatedRequest'

    SearchMessageResponse:
      description: Структура для ответа на запрос поиска объявлений
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            page:
              $ref: '#/components/schemas/BasePaginatedResponse'
            foundAds:
              type: array
              items:
                $ref: '#/components/schemas/ResponseMessage'

    OffersAdRequest:
      description: Структура для запроса поиска предложений для объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseRequest'
        - type: object
          properties:
            page:
              $ref: '#/components/schemas/BasePaginatedRequest'
            deleteAdId:
              type: string
            debug:
              allOf:
                - $ref: '#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - databaseError

    OffersAdResponse:
      description: Структура для ответа на запрос поиска предложений для объявления
      allOf:
        - $ref: '#/components/schemas/BaseMessage'
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            page:
              $ref: '#/components/schemas/BasePaginatedResponse'
            offeredAds:
              type: array
              items:
                $ref: '#/components/schemas/ResponseAd'
